
// the config writes itself (this is what causes the fps problem)


/*clickmefalse*/ function clickmetog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*clickme"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{clickmetog}; /*clickmerightfalse*/ function clickmerighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*clickmeright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{clickmerighttog}
/*othertitlebuttonfalse*/ function othertitlebuttontog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*othertitlebutton"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{othertitlebuttontog}; /*othertitlebuttonrightfalse*/ function othertitlebuttonrighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*othertitlebuttonright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{othertitlebuttonrighttog}
/*togglebuttonfalse*/ function togglebuttontog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*togglebutton"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{togglebuttontog}; /*togglebuttonrightfalse*/ function togglebuttonrighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*togglebuttonright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{togglebuttonrighttog}
/*extratogglebuttonfalse*/ function extratogglebuttontog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*extratogglebutton"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{extratogglebuttontog}; /*extratogglebuttonrightfalse*/ function extratogglebuttonrighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*extratogglebuttonright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{extratogglebuttonrighttog}
/*slider0*/ function slidertog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = 0; fortnite = configfile.split("/*"+"slider").pop().split("*/ "+"function slidertog()")[0]; return fortnite}; export {slidertog}
/*textboxhoverovertotype&f*/ function textboxhoverovertotypetog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = ""; fortnite = configfile.split("/*"+"textboxhoverovertotype").pop().split("*/ "+"function textboxhoverovertotypetog()")[0]; return fortnite}; export {textboxhoverovertotypetog}
/*newbuttonfalse*/ function newbuttontog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*newbutton"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{newbuttontog}; /*newbuttonrightfalse*/ function newbuttonrighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*newbuttonright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{newbuttonrighttog}
/*rightclickmefalse*/ function rightclickmetog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*rightclickme"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{rightclickmetog}; /*rightclickmerightfalse*/ function rightclickmerighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*rightclickmeright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{rightclickmerighttog}
/*ahhhsecretbuttonfalse*/ function ahhhsecretbuttontog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*ahhhsecretbutton"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{ahhhsecretbuttontog}; /*ahhhsecretbuttonrightfalse*/ function ahhhsecretbuttonrighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*ahhhsecretbuttonright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{ahhhsecretbuttonrighttog}
/*extratogglebuttonffalse*/ function extratogglebuttonftog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*extratogglebuttonf"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{extratogglebuttonftog}; /*extratogglebuttonfrightfalse*/ function extratogglebuttonfrighttog() {let configfile = FileLib.read("BadGUI/", "config.js"); let fortnite = false; if (configfile.includes("/*extratogglebuttonfright"+"true*/")) fortnite = true; else fortnite = false; return fortnite}; export{extratogglebuttonfrighttog}
